### Creating one dimensional numpy array (Vector)

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4]) ## one dimensional array

array([1, 2, 3, 4])

In [4]:
a= np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [5]:
type(a)

numpy.ndarray

### Creating two dimensional numpy array (Matrix)

In [6]:
b= np.array([1,2],[3,4])
b

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [7]:
b= np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [8]:
b= np.array([[1,2],[3,4,5,6,7,8]]) ##3 Getting warning
b

C:\Users\bansa\AppData\Local\Temp\ipykernel_19212\2514011870.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b= np.array([[1,2],[3,4,5,6,7,8]])


array([list([1, 2]), list([3, 4, 5, 6, 7, 8])], dtype=object)

In [9]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [10]:
np.array([1,2,3], dtype=bool)

array([ True,  True,  True])

In [11]:
np.array([1,0,3], dtype=bool)

array([ True, False,  True])

In [12]:
np.array([1,0,3], dtype=complex)

array([1.+0.j, 0.+0.j, 3.+0.j])

In [14]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1,10,3)

array([1, 4, 7])

In [17]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [18]:
np.arange(10).reshape(5,3)

ValueError: cannot reshape array of size 10 into shape (5,3)

In [19]:
np.ones(3,4)

TypeError: Cannot interpret '4' as a data type

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((3,4),int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [23]:
np.zeros((3,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
np.random.rand(3,5)

array([[0.77053887, 0.73151262, 0.64308357, 0.47442739, 0.52298392],
       [0.67062085, 0.31446156, 0.70403847, 0.46502531, 0.68577   ],
       [0.97903506, 0.62315644, 0.29863848, 0.00379701, 0.05429743]])

In [25]:
np.random.randn(3,5)

array([[ 0.558212  , -0.60268483, -0.79823274, -1.01530232, -2.18074967],
       [ 0.70119578, -0.9595078 ,  0.77809436, -0.93084259,  1.77174917],
       [ 0.7947254 , -0.07475148, -0.93402658, -1.34207413, -0.18882114]])

In [26]:
np.random.randint(3,5)

4

In [27]:
np.random.randint(3,50)

41

In [28]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [29]:
np.linspace(-2,2,5)

array([-2., -1.,  0.,  1.,  2.])

In [32]:
np.identity(3)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [35]:
np.identity(3,int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [37]:
a1=np.arange(0,10)
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [56]:
a5=np.arange(10,0)
print(a5)

[]


In [40]:
a2=np.arange(10,dtype=float)
print(a2)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [47]:
a2=a2.reshape(2,5)
print(a2)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [59]:
a3=np.arange(8).reshape(2,2,2)
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [45]:
a4=np.arange(27).reshape(3,3,3)
print(a4)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [48]:
a1.ndim

1

In [49]:
a2.ndim

2

In [50]:
a3.ndim

3

In [51]:
a4.ndim

3

In [52]:
a1.shape

(10,)

In [54]:
a1.shape

(10,)

In [55]:
a2.shape

(2, 5)

In [60]:
a3.shape

(2, 2, 2)

In [62]:
a4.shape

(3, 3, 3)

In [63]:
a1.size

10

In [64]:
a2.size

10

In [65]:
a3.size

8

In [66]:
a4.size

27

# Changing data type

In [70]:
x= np.array([1.9,2.0,3.0])
x

array([1.9, 2. , 3. ])

In [71]:
x.astype(int) ## not rounding off, just taking integer part beofore decimal

array([1, 2, 3])

In [72]:
a=np.arange(12).reshape(3,4)

In [73]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
a+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [75]:
a*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [76]:
a/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [77]:
a-5

array([[-5, -4, -3, -2],
       [-1,  0,  1,  2],
       [ 3,  4,  5,  6]])

In [78]:
a**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [79]:
a//2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]], dtype=int32)

In [80]:
a%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

In [83]:
b=np.arange(12).reshape(2,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [84]:
b>2

array([[False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [85]:
a+b

ValueError: operands could not be broadcast together with shapes (3,4) (2,6) 

In [88]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
a+b

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [90]:
a*b

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [91]:
a-b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [92]:
a/b  ### divide  y zero gives warning

C:\Users\bansa\AppData\Local\Temp\ipykernel_19212\1348051284.py:1: RuntimeWarning: invalid value encountered in divide
  a/b


array([[nan,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [94]:
c=np.random.random((3,3))
c

array([[0.88565329, 0.90108855, 0.42812147],
       [0.93540932, 0.46055623, 0.64948256],
       [0.87166031, 0.18272215, 0.95922973]])

In [95]:
a= np.round(c*100)
a

array([[89., 90., 43.],
       [94., 46., 65.],
       [87., 18., 96.]])

In [96]:
np.max(a)

96.0

In [97]:
np.min(a)

18.0

In [98]:
np.sum(a)

628.0

In [99]:
np.prod(a)

1.45533510165888e+16

In [100]:
np.max(a,axis=1)

array([90., 94., 96.])

In [101]:
np.min(a,axis=1)

array([43., 46., 18.])

In [102]:
np.max(a,axis=0)  ### Getting max values in each column

array([94., 90., 96.])

In [106]:
np.prod(a,axis=1) ## Row-wise multiplication

array([344430., 281060., 150336.])

In [107]:
np.mean(a)

69.77777777777777

In [108]:
np.mean(a, axis=1) ### Row-wise mean

array([74.        , 68.33333333, 67.        ])

In [109]:
np.mean(a, axis=0)

array([90.        , 51.33333333, 68.        ])

In [111]:
np.median(a, axis=1)

array([89., 65., 87.])

In [112]:
np.median(a, axis=0)

array([89., 46., 65.])

In [113]:
np.std(a)

26.532067715953662

In [114]:
np.var(a)

703.9506172839506

In [115]:
np.sin(a)

array([[ 0.86006941,  0.89399666, -0.83177474],
       [-0.24525199,  0.90178835,  0.82682868],
       [-0.82181784, -0.75098725,  0.98358775]])

In [116]:
np.cos(a)

array([[ 0.51017704, -0.44807362,  0.5551133 ],
       [ 0.96945937, -0.43217794, -0.56245385],
       [ 0.56975033,  0.66031671, -0.18043045]])

In [117]:
np.tan(a)

array([[ 1.68582537, -1.99520041, -1.49838734],
       [-0.2529781 , -2.08661353, -1.47003826],
       [-1.44241747, -1.13731371, -5.45134011]])