### Numpy: Package for Multidimensional Array

In [2]:
import numpy as np

In [3]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [4]:
 np.arange() # shift+tab -> help box

TypeError: arange() requires stop to be specified.

In [5]:
### two dimensinal array
new_list=[[1,2,3],[4,5,6],[7,8,9]]
arr1=np.array(new_list)

In [6]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(1,10,1,float)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [8]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [9]:
np.zeros(100, int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
np.ones(10,int,"F")

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [11]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
arr5= np.linspace(1,10,20)
arr5

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [27]:
np.random.rand(3,5)

array([[0.87684678, 0.4342087 , 0.58621681, 0.25500799, 0.94744032],
       [0.01450501, 0.45507154, 0.3478144 , 0.90863633, 0.34276719],
       [0.21722829, 0.51626855, 0.96736606, 0.75510092, 0.9373442 ]])

In [18]:
arr2= np.linspace(0,5,20)

In [19]:
arr2

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [20]:
arr2.reshape(2,10)

array([[0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
        1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105],
       [2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
        3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ]])

In [40]:
np.eye((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [43]:
np.random.rand(3,5)

array([[0.6417238 , 0.28392242, 0.52118432, 0.72956813, 0.01251722],
       [0.97101453, 0.58242785, 0.5179279 , 0.68127167, 0.13406565],
       [0.56380574, 0.40812335, 0.65086338, 0.42034835, 0.07651717]])

In [44]:
np.random.randn(5,6)

array([[ 0.42367896, -1.18983104, -1.97929642, -3.2396001 ,  0.23545745,
         0.52668619],
       [ 0.67696014,  0.82633204, -1.28528984,  0.68331109,  0.31432922,
         0.3047767 ],
       [-1.05510537, -2.20457616, -0.92338954,  1.34922245,  0.74331274,
         2.08434974],
       [-0.27839838,  0.42014376,  0.19732437, -1.28382789,  0.62023175,
         1.07592187],
       [-1.14571037,  1.40214281,  1.45887767, -1.30247201,  0.56164012,
        -0.86064544]])

In [45]:
np.random.randint(2,10)

6

In [46]:
np.random.randint(2,10,10)

array([2, 8, 5, 6, 3, 9, 3, 8, 6, 2])

In [47]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr1.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [49]:
arr2

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [50]:
arr2.reshape(1,20)

array([[0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
        1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
        2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
        3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ]])

In [51]:
arr2.max()

5.0

In [52]:
arr2.argmax()

19

In [53]:
a = np.eye(10)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [55]:
arr3= np.random.rand(3,5)

In [57]:
arr3

array([[0.60941334, 0.32419762, 0.81123828, 0.44309093, 0.14726874],
       [0.86971546, 0.91487697, 0.10044383, 0.29057892, 0.11569526],
       [0.96735776, 0.06826626, 0.87373483, 0.0829457 , 0.10466033]])

In [58]:
arr3.T

array([[0.60941334, 0.86971546, 0.96735776],
       [0.32419762, 0.91487697, 0.06826626],
       [0.81123828, 0.10044383, 0.87373483],
       [0.44309093, 0.29057892, 0.0829457 ],
       [0.14726874, 0.11569526, 0.10466033]])

In [63]:
arr4= np.arange(1,21)

In [64]:
arr4.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [65]:
arr5= np.arange(4,51)

In [66]:
arr5

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [67]:
arr5[2]

6

In [68]:
arr5[2:10] # indexing

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [69]:
arr6= np.arange(50,30)

In [70]:
arr6

array([], dtype=int32)

In [71]:
arr5[2:4]=100 # slicing

In [72]:
arr5

array([  4,   5, 100, 100,   8,   9,  10,  11,  12,  13,  14,  15,  16,
        17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
        30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
        43,  44,  45,  46,  47,  48,  49,  50])

In [73]:
subset_arr = arr5[5:30]

In [74]:
subset_arr

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33])

In [75]:
subset_arr[:]=200

In [76]:
subset_arr

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

# Two-Dimensional Array

In [82]:
arr7= np.array(([1,2,3],[1,9,10],[567,5,6]))

In [83]:
arr7

array([[  1,   2,   3],
       [  1,   9,  10],
       [567,   5,   6]])

In [85]:
arr7[2,2]

6

In [87]:
arr7[:]

array([[  1,   2,   3],
       [  1,   9,  10],
       [567,   5,   6]])

In [88]:
arr7[:,(2,1)]

array([[ 3,  2],
       [10,  9],
       [ 6,  5]])

In [91]:
arr7[2,(0,1)]

array([567,   5])

In [92]:
arr7+arr7

array([[   2,    4,    6],
       [   2,   18,   20],
       [1134,   10,   12]])

In [94]:
np.exp(arr7)

array([[2.71828183e+000, 7.38905610e+000, 2.00855369e+001],
       [2.71828183e+000, 8.10308393e+003, 2.20264658e+004],
       [1.75780720e+246, 1.48413159e+002, 4.03428793e+002]])

In [97]:
np.exp(arr7)

array([[2.71828183e+000, 7.38905610e+000, 2.00855369e+001],
       [2.71828183e+000, 8.10308393e+003, 2.20264658e+004],
       [1.75780720e+246, 1.48413159e+002, 4.03428793e+002]])

In [98]:
np.sqrt(arr7)

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 1.        ,  3.        ,  3.16227766],
       [23.8117618 ,  2.23606798,  2.44948974]])

In [99]:
np.square(arr7)

array([[     1,      4,      9],
       [     1,     81,    100],
       [321489,     25,     36]])

In [100]:
arr7

array([[  1,   2,   3],
       [  1,   9,  10],
       [567,   5,   6]])

In [101]:
np.mean(arr7)

67.11111111111111

In [102]:
np.var(arr7)

31245.654320987658

In [103]:
np.argmax(arr7)

6

In [104]:
np.log(arr7)

array([[0.        , 0.69314718, 1.09861229],
       [0.        , 2.19722458, 2.30258509],
       [6.3403593 , 1.60943791, 1.79175947]])

In [105]:
np.std(arr7)

176.76440343289613

In [106]:
np.var(arr7)

31245.654320987658

In [107]:
new_array=np.random.randn(4,5)

In [108]:
new_array

array([[ 0.46435084,  3.16141914,  0.53660636,  1.17719992, -1.05761229],
       [ 0.60323915, -0.47144339,  1.23280396, -1.35395484, -0.86769749],
       [ 0.12004917, -0.60515181, -1.2858011 , -1.16782373,  0.78940807],
       [-0.23502584,  0.35398393,  0.29510079, -1.19230132, -0.40785922]])

In [110]:
np.round(new_array, decimals=2)

array([[ 0.46,  3.16,  0.54,  1.18, -1.06],
       [ 0.6 , -0.47,  1.23, -1.35, -0.87],
       [ 0.12, -0.61, -1.29, -1.17,  0.79],
       [-0.24,  0.35,  0.3 , -1.19, -0.41]])

In [112]:
arr8= np.array(["Golf","football", "cricket","cricket"])

In [113]:
arr8

array(['Golf', 'football', 'cricket', 'cricket'], dtype='<U8')

In [114]:
np.unique(arr8)

array(['Golf', 'cricket', 'football'], dtype='<U8')

### Practice of pre-recorded videos

In [1]:
import seaborn as sns
import pandas as pd
import numpy as np

In [12]:
tips = sns.load_dataset("tips")

URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

In [6]:
df_tips= pd.read_csv("I:/Data Science/Eduonix/Pre-recorded Sessions/seaborn-data-master/tips.csv")

In [7]:
df_tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [9]:
import os

In [11]:
os.getcwd()

'C:\\Users\\bansa'

In [13]:
vehicles={"Type":["Car","Bike","Scooter","Suv","Auto","Sedan"],
          "Cost":[1000,400,300,1200,500,700]}

In [29]:
df_vehicles=pd.DataFrame(vehicles, columns=["Type", "Cost"])

In [30]:
df_vehicles_T = df_vehicles.T 

In [31]:
df_vehicles_T

0     1        2     3     4      5
Type   Car  Bike  Scooter   Suv  Auto  Sedan
Cost  1000   400      300  1200   500    700

In [38]:
df_vehicles_new= df_vehicles_T.rename(columns={df_vehicles_T.columns[0]:"Option 1",
                                               df_vehicles_T.columns[1]:"Option 2",
                                              df_vehicles_T.columns[2]:"Option 3",
                                              df_vehicles_T.columns[3]:"Option 4",
                                              df_vehicles_T.columns[4]:"Option 5",
                                              df_vehicles_T.columns[5]:"Option 6"})

In [39]:
df_vehicles_new

Option 1 Option 2 Option 3 Option 4 Option 5 Option 6
Type      Car     Bike  Scooter      Suv     Auto    Sedan
Cost     1000      400      300     1200      500      700

In [51]:
df_vehicles_flip=df_vehicles_new.T

In [52]:
df_vehicles_flip

Type  Cost
Option 1      Car  1000
Option 2     Bike   400
Option 3  Scooter   300
Option 4      Suv  1200
Option 5     Auto   500
Option 6    Sedan   700

In [42]:
df_vehicles_flip.reset_index

<bound method DataFrame.reset_index of              Type  Cost
Option 1      Car  1000
Option 2     Bike   400
Option 3  Scooter   300
Option 4      Suv  1200
Option 5     Auto   500
Option 6    Sedan   700>

In [53]:
df_vehicles_flip = df_vehicles_flip.reset_index()

In [54]:
df_vehicles_flip

index     Type  Cost
0  Option 1      Car  1000
1  Option 2     Bike   400
2  Option 3  Scooter   300
3  Option 4      Suv  1200
4  Option 5     Auto   500
5  Option 6    Sedan   700

In [58]:
df_vehicles_flip_new = df_vehicles_flip.rename(columns={df_vehicles_flip.columns[0]:"Options"})

In [61]:
df_vehicles_flip_new

Options     Type  Cost
0  Option 1      Car  1000
1  Option 2     Bike   400
2  Option 3  Scooter   300
3  Option 4      Suv  1200
4  Option 5     Auto   500
5  Option 6    Sedan   700

In [62]:
df_vehicles = df_vehicles_flip_new

In [63]:
df_vehicles["Sale Price"]=0.75*df_vehicles["Cost"]

In [66]:
df_vehicles["diff"] = df_vehicles["Sale Price"] - df_vehicles["Cost"]

In [67]:
df_vehicles

Options     Type  Cost Sale Price   diff
0  Option 1      Car  1000      750.0 -250.0
1  Option 2     Bike   400      300.0 -100.0
2  Option 3  Scooter   300      225.0  -75.0
3  Option 4      Suv  1200      900.0 -300.0
4  Option 5     Auto   500      375.0 -125.0
5  Option 6    Sedan   700      525.0 -175.0

In [75]:
df_tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [78]:
tips_by_sex = df_tips.groupby(df_tips["sex"])["tip"].mean()

In [79]:
tips_by_sex

sex
Female    2.833448
Male      3.089618
Name: tip, dtype: float64

In [80]:
df_tips_by_sex= tips_by_sex.reset_index()

In [81]:
df_tips_by_sex

sex       tip
0  Female  2.833448
1    Male  3.089618

In [86]:
tips_by_sex = df_tips.groupby(["sex","smoker"])["tip"].mean()

In [87]:
tips_by_sex

sex     smoker
Female  No        2.773519
        Yes       2.931515
Male    No        3.113402
        Yes       3.051167
Name: tip, dtype: float64

In [88]:
df_tips_by_sex= tips_by_sex.reset_index()

In [89]:
df_tips_by_sex

sex smoker       tip
0  Female     No  2.773519
1  Female    Yes  2.931515
2    Male     No  3.113402
3    Male    Yes  3.051167

In [100]:
this = pd.crosstab(columns=df_tips["sex"], index=[df_tips["smoker"], df_tips["day"],df_tips["time"]]).rename_axis(None, axis=1)

In [101]:
this

Female  Male
smoker day  time                
No     Fri  Dinner       1     2
            Lunch        1     0
       Sat  Dinner      13    32
       Sun  Dinner      14    43
       Thur Dinner       1     0
            Lunch       24    20
Yes    Fri  Dinner       4     5
            Lunch        3     3
       Sat  Dinner      15    27
       Sun  Dinner       4    15
       Thur Lunch        7    10